### ISSUE TITLE
Docs update request: /docs/advanced/proof-of-stake-devnet

### ISSUE THREAD

**Issue by Jayanring** [prysmaticlabs/documentation#860]
Source: https://docs.prylabs.network/docs/advanced/proof-of-stake-devnet

$ ./prysmctl testnet generate-genesis --num-validators=64 --output-ssz=genesis.ssz --chain-config-file=config.yml --override-eth1data=true
INFO[0000] Specified a chain config file: config.yml     prefix=genesis
FATA[0000] Could not generate beacon chain genesis state  error="could not set config params: version 0x04000000 for fork deneb in config interop conflicts with existing config named=mainnet: configset cannot add config with conflicting fork version schedule" prefix=genesis

**Comment by samlaf** [comment]
Also running into similar error:
```
FATA[0000] Could not generate beacon chain genesis state  error="could not set config params: version 0x05000000 for fork electra in config interop conflicts with existing config named=mainnet: configset cannot add config with conflicting fork version schedule" prefix=genesis
```

Changed from `interop` to `minimal` preset:
```
CONFIG_NAME: minimal
PRESET_BASE: minimal
```

but that just runs into more bugs:
```
INFO[0000] Delaying genesis 1725330092 by 600 seconds    prefix=genesis
INFO[0000] Genesis is now 1725330692                     prefix=genesis
INFO[0000] Setting fork geth times                       prefix=genesis shanghai=1725330692
panic: runtime error: index out of range [64] with length 64

goroutine 1 [running]:
github.com/prysmaticlabs/prysm/v5/beacon-chain/state/state-native.(*BeaconState).SetRandaoMixes(0x14000357c08, {0x14001c22008, 0x40, 0x40})
        /Users/samlaf/devel/ethereum/devnet/prysm/beacon-chain/state/state-native/setters_randao.go:29 +0x290
github.com/prysmaticlabs/prysm/v5/runtime/interop.(*PremineGenesisConfig).populate(0x140007966c0, {0x103e49020, 0x14000357c08})
        /Users/samlaf/devel/ethereum/devnet/prysm/runtime/interop/premine-state.go:282 +0x188
github.com/prysmaticlabs/prysm/v5/runtime/interop.(*PremineGenesisConfig).prepare(0x140007966c0, {0x103e1e6b0, 0x10509b8a0})
        /Users/samlaf/devel/ethereum/devnet/prysm/runtime/interop/premine-state.go:81 +0x74
```

**Comment by nikola43** [comment]
https://github.com/OffchainLabs/eth-pos-devnet/blob/5ffb57288ad9dfd21ec99656be12b8319f393cd8/consensus/config.yml

use this file, works for me
